package com.sirius.angular.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.name
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.street
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    private String street;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.city
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.state
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.zip
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    private String zip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.country
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.giftwrap
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    private Boolean giftwrap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.products
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    private String products;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "GMT+08:00")
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.name
     *
     * @return the value of order.name
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.name
     *
     * @param name the value for order.name
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.street
     *
     * @return the value of order.street
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.street
     *
     * @param street the value for order.street
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.city
     *
     * @return the value of order.city
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.city
     *
     * @param city the value for order.city
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.state
     *
     * @return the value of order.state
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.state
     *
     * @param state the value for order.state
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.zip
     *
     * @return the value of order.zip
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.zip
     *
     * @param zip the value for order.zip
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.country
     *
     * @return the value of order.country
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.country
     *
     * @param country the value for order.country
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.giftwrap
     *
     * @return the value of order.giftwrap
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    public Boolean getGiftwrap() {
        return giftwrap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.giftwrap
     *
     * @param giftwrap the value for order.giftwrap
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    public void setGiftwrap(Boolean giftwrap) {
        this.giftwrap = giftwrap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.products
     *
     * @return the value of order.products
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    public String getProducts() {
        return products;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.products
     *
     * @param products the value for order.products
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    public void setProducts(String products) {
        this.products = products == null ? null : products.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_time
     *
     * @return the value of order.create_time
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_time
     *
     * @param createTime the value for order.create_time
     *
     * @mbggenerated Fri Jul 14 11:41:33 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}