package com.piaolink.admin.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;

import java.io.Serializable;
import java.util.Date;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class User implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile_no
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private String mobileNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.company_name
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.position
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.area
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.province
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.city
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.district
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.picture
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.date_create
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "GMT+08:00")
    private Date dateCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.platform
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private Integer platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.reg_uid
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private String regUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.my_uid
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private String myUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.office_phone
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private String officePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.namecard_url
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private String namecardUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.bussiness_license_url
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private String bussinessLicenseUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.jd_account
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private String jdAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.validation_result
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    private String validationResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.update_time
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    @JsonFormat(pattern="yyyy-MM-dd", timezone = "GMT+08:00")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.reg_count
     *
     * @mbggenerated Fri May 12 16:25:31 CST 2017
     */
    private Integer regCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.reg_update_time
     *
     * @mbggenerated Fri May 12 16:25:31 CST 2017
     */
	@JsonFormat(pattern="yyyy-MM-dd", timezone = "GMT+08:00")
    private Date regUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile_no
     *
     * @return the value of user.mobile_no
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile_no
     *
     * @param mobileNo the value for user.mobile_no
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo == null ? null : mobileNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gender
     *
     * @return the value of user.gender
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gender
     *
     * @param gender the value for user.gender
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.company_name
     *
     * @return the value of user.company_name
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.company_name
     *
     * @param companyName the value for user.company_name
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.position
     *
     * @return the value of user.position
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.position
     *
     * @param position the value for user.position
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.area
     *
     * @return the value of user.area
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.area
     *
     * @param area the value for user.area
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.province
     *
     * @return the value of user.province
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.province
     *
     * @param province the value for user.province
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.city
     *
     * @return the value of user.city
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.city
     *
     * @param city the value for user.city
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.district
     *
     * @return the value of user.district
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.district
     *
     * @param district the value for user.district
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.picture
     *
     * @return the value of user.picture
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.picture
     *
     * @param picture the value for user.picture
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.date_create
     *
     * @return the value of user.date_create
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public Date getDateCreate() {
        return dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.date_create
     *
     * @param dateCreate the value for user.date_create
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setDateCreate(Date dateCreate) {
        this.dateCreate = dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.platform
     *
     * @return the value of user.platform
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public Integer getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.platform
     *
     * @param platform the value for user.platform
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.reg_uid
     *
     * @return the value of user.reg_uid
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public String getRegUid() {
        return regUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.reg_uid
     *
     * @param regUid the value for user.reg_uid
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setRegUid(String regUid) {
        this.regUid = regUid == null ? null : regUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.my_uid
     *
     * @return the value of user.my_uid
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public String getMyUid() {
        return myUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.my_uid
     *
     * @param myUid the value for user.my_uid
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setMyUid(String myUid) {
        this.myUid = myUid == null ? null : myUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.office_phone
     *
     * @return the value of user.office_phone
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public String getOfficePhone() {
        return officePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.office_phone
     *
     * @param officePhone the value for user.office_phone
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setOfficePhone(String officePhone) {
        this.officePhone = officePhone == null ? null : officePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.namecard_url
     *
     * @return the value of user.namecard_url
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public String getNamecardUrl() {
        return namecardUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.namecard_url
     *
     * @param namecardUrl the value for user.namecard_url
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setNamecardUrl(String namecardUrl) {
        this.namecardUrl = namecardUrl == null ? null : namecardUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.bussiness_license_url
     *
     * @return the value of user.bussiness_license_url
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public String getBussinessLicenseUrl() {
        return bussinessLicenseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.bussiness_license_url
     *
     * @param bussinessLicenseUrl the value for user.bussiness_license_url
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setBussinessLicenseUrl(String bussinessLicenseUrl) {
        this.bussinessLicenseUrl = bussinessLicenseUrl == null ? null : bussinessLicenseUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.jd_account
     *
     * @return the value of user.jd_account
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public String getJdAccount() {
        return jdAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.jd_account
     *
     * @param jdAccount the value for user.jd_account
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setJdAccount(String jdAccount) {
        this.jdAccount = jdAccount == null ? null : jdAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.validation_result
     *
     * @return the value of user.validation_result
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public String getValidationResult() {
        return validationResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.validation_result
     *
     * @param validationResult the value for user.validation_result
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setValidationResult(String validationResult) {
        this.validationResult = validationResult == null ? null : validationResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.update_time
     *
     * @return the value of user.update_time
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.update_time
     *
     * @param updateTime the value for user.update_time
     *
     * @mbggenerated Thu May 04 20:07:58 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.reg_count
     *
     * @return the value of user.reg_count
     *
     * @mbggenerated Fri May 12 16:25:31 CST 2017
     */
    public Integer getRegCount() {
        return regCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.reg_count
     *
     * @param regCount the value for user.reg_count
     *
     * @mbggenerated Fri May 12 16:25:31 CST 2017
     */
    public void setRegCount(Integer regCount) {
        this.regCount = regCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.reg_update_time
     *
     * @return the value of user.reg_update_time
     *
     * @mbggenerated Fri May 12 16:25:31 CST 2017
     */
    public Date getRegUpdateTime() {
        return regUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.reg_update_time
     *
     * @param regUpdateTime the value for user.reg_update_time
     *
     * @mbggenerated Fri May 12 16:25:31 CST 2017
     */
    public void setRegUpdateTime(Date regUpdateTime) {
        this.regUpdateTime = regUpdateTime;
    }
}