package com.piaolink.admin.mapper;

import com.piaolink.admin.entity.OpAdmin;

public interface OpAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_admin
     *
     * @mbggenerated Wed Apr 26 17:43:31 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_admin
     *
     * @mbggenerated Wed Apr 26 17:43:31 CST 2017
     */
    int insert(OpAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_admin
     *
     * @mbggenerated Wed Apr 26 17:43:31 CST 2017
     */
    int insertSelective(OpAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_admin
     *
     * @mbggenerated Wed Apr 26 17:43:31 CST 2017
     */
    OpAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_admin
     *
     * @mbggenerated Wed Apr 26 17:43:31 CST 2017
     */
    int updateByPrimaryKeySelective(OpAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_admin
     *
     * @mbggenerated Wed Apr 26 17:43:31 CST 2017
     */
    int updateByPrimaryKey(OpAdmin record);

    OpAdmin selectByUserName(String userName);
}