package com.piaolink.admin.mapper;

import com.piaolink.admin.entity.OpAuditLog;

public interface OpAuditLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_audit_log
     *
     * @mbggenerated Wed Apr 26 17:43:31 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_audit_log
     *
     * @mbggenerated Wed Apr 26 17:43:31 CST 2017
     */
    int insert(OpAuditLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_audit_log
     *
     * @mbggenerated Wed Apr 26 17:43:31 CST 2017
     */
    int insertSelective(OpAuditLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_audit_log
     *
     * @mbggenerated Wed Apr 26 17:43:31 CST 2017
     */
    OpAuditLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_audit_log
     *
     * @mbggenerated Wed Apr 26 17:43:31 CST 2017
     */
    int updateByPrimaryKeySelective(OpAuditLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_audit_log
     *
     * @mbggenerated Wed Apr 26 17:43:31 CST 2017
     */
    int updateByPrimaryKey(OpAuditLog record);
}