package com.piaolink.admin.mapper;

import com.piaolink.admin.entity.User;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Apr 26 17:10:39 CST 2017
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Apr 26 17:10:39 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Apr 26 17:10:39 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Apr 26 17:10:39 CST 2017
     */
    User selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Apr 26 17:10:39 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Apr 26 17:10:39 CST 2017
     */
    int updateByPrimaryKey(User record);

    /**
     * Example
     * @return
     */
    List<User> getUsers();
    List<User> selectByLikeId(String id);
    List<User> selectByValidation(String validation);
    List<User> selectLikePhone(String phone);
    User selectByPhone(String phone);
    List<User> selectLikeName(String name);
    User selectByName(String name);
    List<User> selectLikeUsername(String username);
    User selectByUsername(String username);
    List<User> selectLikeCreatetime(@Param("begin") Date begin,@Param("end") Date end);
    List<User> selectByReguid(String reguid);
}