server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  server:
    eviction-interval-timer-in-ms: 4000
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/